### ISSUE TITLE
Mysensors binding [channel names disappearing in paperui control page after OH2 restart]

### ISSUE THREAD

**Issue by rocket59** [tobof/openhab2-addons#102]
Openhab 2.2 installed via apt (raspbian jessie)
Mysensors binding installed via IOT marketplace (market:binding-3328323 - 1.0)

Possible bug is as described here:
https://community.openhab.org/t/mysensors-binding-channel-names-disappearing-in-paperui-control-page-after-reboot/35706

Workaround is given in the 2nd post of the above thread.

**Comment by rocket59** [comment]
Note: potential solution is posted towards the end of the thread by a contributor.

**Comment by tobof** [comment]
I'm not able to reproduce this error with the current code base. I suppose it was fixed with an update for OpenHAB2.
