### ISSUE TITLE
Serial bunding no working well with other serial devices

### ISSUE THREAD

**Issue by stas-dovgodko** [tobof/openhab2-addons#103]
mysensors serial + rflink serial in hyper-v with virtual usb:
```
Bus 001 Device 009: ID 2341:0042 Arduino SA Mega 2560 R3 (CDC ACM)  <-- RFlink
Bus 001 Device 008: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter  <-- mysensors
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub 
```

but mysensors looks like bound all serial to self:

```
12:55:36.348 [DEBUG] [col.serial.MySensorsSerialConnection] - Connecting to /dev/mysensors [baudRate:115200]
12:55:36.465 [DEBUG] [col.serial.MySensorsSerialConnection] - Final port list: /dev/ttyACM1:/dev/ttyUSB2:/dev/ttyS1:/dev/ttyS0:/dev/mysensors

```

Here /dev/ttyACM1 is RFlink port. And after that RFlink stops working

**Comment by tobof** [comment]
The debug output "Final port list ..." is only an information. It does not mean that the MySensors binding is using this port.

Are you using the RFLink binding for OpenHAB2?

I too have connected two USB devices to my system: one for MySensors and the other one for ebusd (not the OpenHAB2 binding) and don't have any problems.

**Comment by stas-dovgodko** [comment]
> Are you using the RFLink binding for OpenHAB2?

Yes but with the help of virtualhere - virtual USB to hyper-v(win2016) container(ubuntu). Both works well in separate but not both (

**Comment by tobof** [comment]
Is there any output from the RFLink binding, that may be of help here?
