### ISSUE TITLE
Question: ESP8266 + Openhab

### ISSUE THREAD

**Issue by lblabr** [tobof/openhab2-addons#127]
Hi,

i like to use the ESP8266 with espurna firmware. i started to use openhab, what i would like to have is the autodiscover function for my esp's. more or less are there sensors sometimes actors.

could i mix mysensors lib with espurna, to use your binding, it seems there is a lot of functionality already there ....

to automate the configuration task is the main aspect i would like to achive.... MQTT, REST and webosckets are supported by espurna.... 

can you give me some hints ?

thanks in advanc

Lars

**Comment by tobof** [comment]
@lblabr I don't think this is possible. 
MySensors and espurna are similar in the functionality.
You are able to create a MQTT Gateway with attached sensors / actuators based on an ESP8266 node (WLAN) with the MySensors binding. So you don't need espurna.

On the other side the learning curve for espurna seems very steep and if you already have some nodes running fine you may live without the discovery functionality (or create a OpenHAB binding for espurna) :-)

It really depends on your use case and what you want to achieve.

**Comment by lblabr** [comment]
i like to have a webui and rest .... i will think about it...
