### ISSUE TITLE
bindings arent updating items

### ISSUE THREAD

**Issue by RonniePitts** [tobof/openhab2-addons#22]
I cant seem to get the mysensor bridge to update the items: 

Debug output suggests its reading the serial data correctly.

17:00:27.285 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;1;1;0;0;19.0
17:00:27.347 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=2,c=1,t=0,pt=7,l=5,sg=0:19.1
17:00:27.347 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;2;1;0;0;19.1
17:00:32.761 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=0,c=1,t=0,pt=7,l=5,sg=0:25.1
17:00:32.765 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;0;1;0;0;25.1
17:00:32.810 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=1,c=1,t=0,pt=7,l=5,sg=0:19.0

However OH2 doesnt update. 
The auto discovery in things worked, hence it created the 3 sensors I have.

I've tried manually updating the things and items and still no luck. 

things conf:

Bridge mysensors:bridge-ser:gateway [ serialPort="/dev/arduino", sendDelay=200 ] {
    temperature     temp01  [ nodeId="105", childId="1" ]
  }

Items   
 Number temp01 { channel="mysensors:temperature:gateway:temp01:temp" }

**Comment by andreacioni** [comment]
Hi Ronnie,
Have you try to link channel thing to item from Paper UI? It is the best way to avoid mistake in configuration files. 
Il 31 Lug 2016 09:07, RonniePitts <notifications@github.com> ha scritto:I cant seem to get the mysensor bridge to update the items: 

Debug output suggests its reading the serial data correctly.

17:00:27.285 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;1;1;0;0;19.0
17:00:27.347 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=2,c=1,t=0,pt=7,l=5,sg=0:19.1
17:00:27.347 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;2;1;0;0;19.1
17:00:32.761 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=0,c=1,t=0,pt=7,l=5,sg=0:25.1
17:00:32.765 [DEBUG] [col.serial.MySensorsSerialConnection] - 105;0;1;0;0;25.1
17:00:32.810 [DEBUG] [col.serial.MySensorsSerialConnection] - 0;0;3;0;9;read: 105-105-0 s=1,c=1,t=0,pt=7,l=5,sg=0:19.0

However OH2 doesnt update. 
The auto discovery in things worked, hence it created the 3 sensors I have.

I've tried manually updating the things and items and still no luck. 

things conf:

Bridge mysensors:bridge-ser:gateway [ serialPort="/dev/arduino", sendDelay=200 ] {
    temperature     temp01  [ nodeId="105", childId="1" ]
  }

Items
 Number temp01 { channel="mysensors:temperature:gateway:temp01:temp" }

**Comment by RonniePitts** [comment]
Yeah, I've go down that path as well. Basically used the discovery method in Paper UI which did correctly pickup my 3 sensors.

**Comment by tobof** [comment]
Please check if the channel of a thing is really linked against an item.
You are able to search for a debug output or via PaperUI if you edit the thing. The circle at the beginning of the channel must be filled.

I rarely see this bug too and after deleting the "userdata" directory which contains the mapdb or linking the item manually as described above everything works fine.
