### ISSUE TITLE
Motion sensor does not work

### ISSUE THREAD

**Issue by sSpeaker** [tobof/openhab2-addons#31]
I'm trying to use this binding on the latest version of Openhab (2.0.0.b4 Build #477), but it does not work well.

Here is my things config:
`Bridge mysensors:bridge-ser:gateway [ serialPort="/dev/ttyUSB0", sendDelay=200 ] {
        humidity        hum01   [ nodeId="3", childId="1" ]
        motion          mot01   [ nodeId="3", childId="3" ]
}`
items:
`Number hum01    "Humidity" { channel="mysensors:humidity:gateway:hum01:hum" }
Number mot01    "Motion" { channel="mysensors:motion:gateway:mot01:tripped" }`

Log:
`11:15:30.369 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;255;3;0;0;96
11:15:30.375 [DEBUG] [g.mysensors.handler.MySensorsHandler] - Setting last update for node 3 to 2016-09-26T11:15:30.372-0400
11:15:30.634 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;3;1;0;16;1
11:15:30.893 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;0;1;0;23;26
11:15:31.157 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;2;1;0;0;25.1
11:15:31.420 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;1;1;0;1;45.8
11:15:31.440 [INFO ] [marthome.event.ItemStateChangedEvent] - hum01 changed from NULL to 45.8
11:15:31.680 [DEBUG] [g.mysensors.protocol.MySensorsReader] - 3;4;1;0;4;744.4
`
As you can see hum01 was updated, but mot01 was ignored. The same thing is with a "sound" type(V_LEVEL).

**Comment by tobof** [comment]
Please change:
`Number mot01`
To:
`Contact mot01`

My motion sensor is running fine, so it should work. Mine is exactly configured like the example in the Wiki.

**Comment by sSpeaker** [comment]
Yep, you are right. The problem was in the item type.  With the binding  from Openhab 1.x item type was not matter. Thanks.
