### ISSUE TITLE
[new message-type] S_IR (V_IR_SEND, V_IR_RECEIVE)

### ISSUE THREAD

**Issue by gersilex** [tobof/openhab2-addons#32]
I'd like to use my IR Proxy with the new binding. If you find the time, it would be awesome if you could add these types. They don't do anything special so it should work flawlessly.

I'll also try to set up openhab2 development on my machine, but don't expect to much. Last time I failed.

Thank you!

**Comment by tobof** [comment]
S_IR is implemented now!

**Comment by gersilex** [comment]
Wow that was fast. Thank you very much.

>

**Comment by tobof** [comment]
There currently is an issue that prevents building a new jar. The new feature is not yet available in the binary.
