### ISSUE TITLE
Package build fails: Type mismatch: cannot convert from List<Object> to List<Integer>

### ISSUE THREAD

**Issue by tobof** [tobof/openhab2-addons#35]
A "mvn clean package" in the directory "addons/binding/org.openhab.binding.mysensors/" results in: 

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.openhab.binding.mysensors: Compilation failure: Compilation failure:
[ERROR] /home/toberfoe/git/openhab2-addons/addons/binding/org.openhab.binding.mysensors/src/main/java/org/openhab/binding/mysensors/internal/handler/MySensorsBridgeHandler.java:[163]
[ERROR] List<Integer> givenIds = Arrays
[ERROR] .stream(cacheFactory.readCache(MySensorsCacheFactory.GIVEN_IDS_CACHE_FILE, new int[] {}, int[].class))
[ERROR] .boxed().collect(Collectors.toList());
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from List<Object> to List<Integer>
[ERROR] /home/toberfoe/git/openhab2-addons/addons/binding/org.openhab.binding.mysensors/src/main/java/org/openhab/binding/mysensors/internal/handler/MySensorsBridgeHandler.java:[197]
[ERROR] List<Integer> givenIds = Arrays
[ERROR] .stream(cacheFactory.readCache(MySensorsCacheFactory.GIVEN_IDS_CACHE_FILE, new int[] {}, int[].class))
[ERROR] .boxed().collect(Collectors.toList());
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from List<Object> to List<Integer>
[ERROR] /home/toberfoe/git/openhab2-addons/addons/binding/org.openhab.binding.mysensors/src/main/java/org/openhab/binding/mysensors/internal/handler/MySensorsBridgeHandler.java:[234]
[ERROR] List<Integer> givenIds = Arrays.stream(
[ERROR] cacheFactory.readCache(MySensorsCacheFactory.GIVEN_IDS_CACHE_FILE, new int[] {}, int[].class))
[ERROR] .boxed().collect(Collectors.toList());
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by andreacioni** [comment]
Yes, known issue. No solution found yet. There's something strange in mvn plugin that doesn't recognise lambda expressions.
I'll try to investigate it one more time tonignt.

In the meantime, could you build the jar through Eclipse->Export->Deployable Plugins and fragment?



Il 19 Ott 2016 14:37, tobof <notifications@github.com> ha scritto:

**Comment by andreacioni** [comment]
Ok, seems to be resolved in last PR.
Could you check too?

Thanks!

**Comment by tobof** [comment]
Solved!
