### ISSUE TITLE
After discovery things don't change its online status to "ONLINE"

### ISSUE THREAD

**Issue by tobof** [tobof/openhab2-addons#38]
https://forum.mysensors.org/topic/5296/offline-status-on-sensor-and-nan-values/2

Reboot solves the problem. Not dependent on the OH2 version.

**Comment by andreacioni** [comment]
Hi Tim!
I think I've introduced this bug in the last refactoring. Please note that only [here](https://github.com/tobof/openhab2-addons/blob/MySensors/addons/binding/org.openhab.binding.mysensors/src/main/java/org/openhab/binding/mysensors/internal/handler/MySensorsThingHandler.java#L78) the binding update the state of a thing. So only when bridge go offline/online the status changes. Probably the solution is to initialize the thing with the status of the bridge on creation. What do you think?

**Comment by tobof** [comment]
Solved!
