### ISSUE TITLE
Change to OH2 (replacement of org.openhab.io.transport.serial by nrjavaserial) breaks mysensors plugin

### ISSUE THREAD

**Issue by johannrichard** [tobof/openhab2-addons#45]
A few days ago, the OpenHAB team replaced the serial transport binding in favour of the nrjavaserial binding. This breaks mysensors in the current build. 

(In commit https://github.com/openhab/openhab-core/commit/99b64815c9c9cf018a1d869ce21696512720310a, see https://github.com/openhab/openhab-core/pull/104)

**Comment by andreacioni** [comment]
Hi Johann,
I've alredy noticed that with new openhab sdk this binding not compile. Just to organize myself, are you planning to fix this issue?

**Comment by kaikreuzer** [comment]
All you need to do is to update your target platform, i.e. pull this commit from openhab-distro: https://github.com/openhab/openhab-distro/commit/1343cc5df62e18785ac9be726fdc7485224e8a5e

**Comment by johannrichard** [comment]
@kaikreuzer Thanks for the hint, wasn't aware it's that simple. 👍 
@andreacioni I'm not working actively on this binding. But as @kaikreuzer points out, it's merely a question of having the build updated. For this repo, it's something that @tobof has to do. Or you clone the repo and build your own release of the mysensors binding.

**Comment by andreacioni** [comment]
Perfect 😄 thanks for the help to everyone.

**Comment by tobof** [comment]
Thank you very much for the input. Runs fine with Snapshot 684 for me.
