### ISSUE TITLE
armed-channel should be a switch item?

### ISSUE THREAD

**Issue by tofverstedt** [tobof/openhab2-addons#52]
I believe that the armed type for example motion sensors is a command sent from the controller to the sensor.

Suggestion: Change armed-channel to a switch item so it is possible to send armed commands to sensors.

**Comment by andreacioni** [comment]
Hi @tofverstedt 

I've never used armed-channel. However, could your question be related to an open issue: [#24](https://github.com/tobof/openhab2-addons/issues/24)? We are discussing it right now 😉

**Comment by tofverstedt** [comment]
@andreaceoni
I have sen that issue but i believe it is two different questions.
#24 is related to how an incoming command is handled in openhab.
My issue, which in my opinion is a bug, is related to how an outgoing command can be enabled. The armed message type is sent from the controller to the sensor. It is not possible to sendCommand to a contact item in openhab.

**Comment by tobof** [comment]
I agree with @tofverstedt and will fix it!
