### ISSUE TITLE
messages are sent multiple times

### ISSUE THREAD

**Issue by fipilica** [tobof/openhab2-addons#61]
With an arduino pro mini driving a 5v relay module, turning on and off a bunch of LEDs, Openhab2 log is showing multiple ACK sent. Behavior is not consistent :)
![capture](https://cloud.githubusercontent.com/assets/18039343/22524875/adb4add8-e8cd-11e6-814d-c7702538bd7c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/18039343/22524883/b424ee9e-e8cd-11e6-8339-7375f13e4da2.PNG)
I attached the items and things
[config_files.zip](https://github.com/tobof/openhab2-addons/files/746068/config_files.zip)

**Comment by tobof** [comment]
Thank you for reporting this issue.
Looks like there is a bug in the ACK - mechanism of the binding.

We'll fix this after (or with) the refactoring.

**Comment by andreacioni** [comment]
Found a possible race condition in MySensorsWriter thread. When we get the message from the blocking queue and we start to process it, Reader thread could try to remove acknowledged message but fail because Writer has not yet re-inserted the message in queue.

**Comment by andreacioni** [comment]
PR #64 now contain a fix for this issue, commit: [99d9c7b](https://github.com/tobof/openhab2-addons/pull/64/commits/99d9c7b659f34d947adfc3f9dfa39d82b6fbd5cb)
