### ISSUE TITLE
Gateway restart 

### ISSUE THREAD

**Issue by fipilica** [tobof/openhab2-addons#62]
Using the same setup as described there #61, when the node driving the relay is offline  I get the following output in OpenHab.
![screen_log](https://cloud.githubusercontent.com/assets/18039343/22550571/597bc332-e959-11e6-9470-11085286e2ca.JPG)
I attached the items and things files and also part of the openhab log for easier copy paste :-)
[config_files.zip](https://github.com/tobof/openhab2-addons/files/747779/config_files.zip)
[openhab_log.zip](https://github.com/tobof/openhab2-addons/files/747780/openhab_log.zip)

If there is something else you need me to try just let me know.

**Comment by tobof** [comment]
Weird! Could you please test with another controller or serial terminal? 
For example with MYSController: https://www.mysensors.org/controller/myscontroller

**Comment by fipilica** [comment]
Hi tobof,
With the latest openhab2 release and the library from wiki link I can not reproduce this bug.

**Comment by tobof** [comment]
@fipilica Thank you for reporting back. I'll close this issue because the problem seems to be solved.
