### ISSUE TITLE
Same parameter for all things (except the bridge)

### ISSUE THREAD

**Issue by andreacioni** [tobof/openhab2-addons#63]
Hello @tobof ! 
I'm wondering to put in each "config-description" tag (inside  _thing-types_ file) all the parameters contained in MySensorsThingConfig.java . This allows user to set, for example, smartSleep to a Motion Sensor (it has the armed channel) and simplify, for us, the update of that file. I told you that because I'm now adding new configurable parameters and I've encountered some difficulties. Clearly I'll do this on "Refactoring" branch. 
What do you think? 😃

**Comment by andreacioni** [comment]
I'll attach [here](https://github.com/tobof/openhab2-addons/files/755403/thing-types.xml.zip) the resulting file.

**Comment by tobof** [comment]
Good idea!

In addition we should split the xml file. 
An approach like this one looks neat: https://github.com/openhab/org.openhab.binding.zwave/tree/master/ESH-INF/thing

**Comment by andreacioni** [comment]
Hmmm yes it will be more readable than now 👍 . Today I'll push the modification with updated thing-type file. We can leave open this ticket as a TODO for splitting that file later.
