### ISSUE TITLE
thing-types.xml: hvacThermostat thing type is missing boolean status-channel

### ISSUE THREAD

**Issue by aivarlo** [tobof/openhab2-addons#78]
According to MySensors serial protocol thermostat has binary status parameter, afaiu thing-types.xml misses that (and I miss it too:) Maybe adding `<channel id="status" typeId="status-channel" />` to hvacThermostat definition would be enough to fix that, no?

**Comment by tobof** [comment]
Yes, this should be sufficient. I'm currently on my phone but will update the code soon.
