### ISSUE TITLE
customSensor not updating variables

### ISSUE THREAD

**Issue by creynlds** [tobof/openhab2-addons#80]
Please see MySensors post for details: [https://forum.mysensors.org/topic/1598/openhab-2-0-binding/448]

**Comment by creynlds** [comment]
TimO, I stand corrected, the variables are being updated. I was fooled by the log. For some reason the log does not show the change the way it did it binding 2.0.0. I placed debug messages in my rules and they're  updating. I will leave this open in case you want to take a look at the logging change, otherwise you can close it. Thanks again for the binding.

**Comment by tobof** [comment]
@creynlds Thank you for the update. The logging indeed changed with the refactoring.

From time to time I too get fooled by the OpenHab log. If a new status is received with the same value / content there is no entry in the INFO log about the update.
