### ISSUE TITLE
Automatic door configuration

### ISSUE THREAD

**Issue by stefaanv** [tobof/openhab2-addons#82]
How can an automatic door be configured ?
The door is presented as S_LOCK (child_id=5), data is sent and received with V_LOCK_STATUS
How must the mysensors binding in openHab be configured to make this work ?
I'd like to see the door status in openHab but I also want to be able to open/close the door from openHab.
Is this possible ?

**Comment by tobof** [comment]
The easiest way would be to use autodiscovery. This should work just fine.

It is possible to receive the status from the sensor and to send it. Lock is represented as a switch in OpenHab.

The definition should look like this (untested):

things:
`lock lock01 [ nodeId="10", childId="5" ]`

items:
`Switch lock01 "Lock 1" (gGroup) { channel="mysensors:lock:gateway:lock01:lock-status" }`
