### ISSUE TITLE
RGBW node definition via things file doesn't work

### ISSUE THREAD

**Issue by OliverHi** [tobof/openhab2-addons#88]
I am running openhab 2.1.0 and the version 2.2.0.201707241115 of the MySensors binding on a raspberry pi.

I have defined several things via a *.things file.

```
Bridge mysensors:bridge-ser:gwSerial [ serialPort="/dev/ttyUSB0", sendDelay=100 ] {

    /** Lights */
    rgbwLight 		LichtKuecheUnten	[nodeID=4, childId=1, requestAck=true]
  	rgbwLight 		LichtFenster 		[nodeID=5, childId=1, requestAck=true]
  	rgbwLight 		LichtSchrank 		[nodeID=6, childId=1, requestAck=true]
  	rgbwLight 		LichtWand 			[nodeID=7, childId=1, requestAck=true]

	/** Sensors */	
	temperature		tempBad				[nodeId=8, childId=0]
  	humidity 		humBad 				[nodeId=8, childId=1]
	temperature		tempWohnzimmer		[nodeId=1, childId=0]
  	humidity 		humWohnzimmer		[nodeId=1, childId=1]
  	light-level		lightWohnzimmer		[nodeId=17, childId=1]
}
```

All sensors are working just fine. They show up in the paperUI, initialize and show the updated values. The rgbw nodes don't. They don't get initialized. The nodeID and childId settings are correct, I use the same values with domoticz.
![image](https://user-images.githubusercontent.com/9283757/29194505-334bce26-7e2a-11e7-930c-57d1b597b10d.png)

The items do pop up as new things in the inbox though (after restarting the nodes so that they present themselves). I can add them there and use them. This should be the thing "LichtKuecheUnten" from above. 
![image](https://user-images.githubusercontent.com/9283757/29194557-753dd860-7e2a-11e7-8555-f83f1b799653.png)

**Comment by tobof** [comment]
It's `nodeId`, not `nodeID`! :smiley: 

Should work with that change.

I've tested it with:

```
Bridge mysensors:bridge-ser:MySGWRFM [ serialPort="/dev/pts/6", sendDelay=60, startupCheckEnabled=false ] {
    rgbwLight       LichtKuecheUnten    [ nodeId=4, childId=1, requestAck=false]
}
```

**Comment by OliverHi** [comment]
Ups that's embarrassing. Thanks for the hint.
I tested it with `nodeId` and it's working just fine now.
