### ISSUE TITLE
VAR1,...,VAR5 channel on every thing

### ISSUE THREAD

**Issue by andreacioni** [tobof/openhab2-addons#95]
Issue opened due to a lot of people asking for this feature on:

- **MySensors Forum**:
  - [#523](https://forum.mysensors.org/topic/1598/openhab-2-0-binding/523)
  - [#511](https://forum.mysensors.org/topic/1598/openhab-2-0-binding/511)

- **GitHub**: 
   - [#65](https://github.com/tobof/openhab2-addons/issues/65#issuecomment-325110081)

**Comment by fab33** [comment]
I don't think it's a good idea. You can add childId with variables you need.

**Comment by andreacioni** [comment]
Yes you could. But not I'm not sure it is the best approach. If we use your suggested solution we must consider, in order to avoid confusion, to remove channels `var1,...,var5` from all things that already define them (i.e. `humidity`, `temperature`, `waterMeter`, etc...). Clearly we must keep 'customSensor' because it will be the one that holds `var1,...,var5` channels.
By now I've not idea what is the best way, but I believe that we have only 2 possibilities:
- Add `var1,...,var5` to all things
- Remove `var1,...,var5` from all things (except 'customSensor')

**Comment by micktech** [comment]
It would be great to have this option available. The irrigation sketch I am using has 8 binary outputs, all with variable1-3 in use for times/naming. Creating a childid for each zone variable would mean 24+ new child IDs, It would be much neater having var1-5 available as things.
