### ISSUE TITLE
MQTT dependency error

### ISSUE THREAD

**Issue by andreacioni** [tobof/openhab2-addons#98]
Hi @tobof, I finally found some time to spent on this error 😅
I found out a possible solution but I'm not able to test it. In particular I've changed:
- `META-INF/MANIFEST.MF` (Import-Package section)
  - `org.openhab.core.events -> org.eclipse.smarthome.core.events`
  - `org.openhab.io.transport.mqtt ->  org.eclipse.smarthome.io.transport.mqtt`

After that I've adjusted the import inside `MySensorsMqttConnection.java` and `MySensorsMqttService.java` and everything compile (with some deprecation warnings). 

Hope this helps!

**Comment by tobof** [comment]
As expected the smarthome.io.transport.mqtt library has changed.
I don't want to rely a new feature on deprecated classes / methods. As I don't see a single plugin based on smarthome.io.transport.mqtt (except from mqqt.test ;-)) I'm not sure if the library is still work in progress.
